### ISSUE TITLE
making the UI/UX of the game more user friendly

### ISSUE THREAD

**Issue by adisuyash** [adisuyash/rock-paper-scissors#1]
Instead of black background, use coloured background,
a simple, user friendly colour pallete and design the game properly

**Comment by NereidaRondon** [comment]
Hi @adisuyash, may I please be assigned this issue? Thanks in advance.

**Comment by adisuyash** [comment]
> Hi @adisuyash, may I please be assigned this issue? Thanks in advance.

Yes go ahead Nereida
